// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v3.21.12
// source: samples_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MessageSenderClient is the client API for MessageSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageSenderClient interface {
	Send(ctx context.Context, in *MessageRequest, opts ...grpc_go.CallOption) (*MessageResponse, common.ErrorWithAttachment)
}

type messageSenderClient struct {
	cc *triple.TripleConn
}

type MessageSenderClientImpl struct {
	Send func(ctx context.Context, in *MessageRequest) (*MessageResponse, error)
}

func (c *MessageSenderClientImpl) GetDubboStub(cc *triple.TripleConn) MessageSenderClient {
	return NewMessageSenderClient(cc)
}

func (c *MessageSenderClientImpl) XXX_InterfaceName() string {
	return "MessageSender"
}

type MessageSenderClientImpl2 struct {
	Send func(ctx context.Context, in *MessageRequest) (*MessageResponse, error)
}

func (c *MessageSenderClientImpl2) GetDubboStub(cc *triple.TripleConn) MessageSenderClient {
	return NewMessageSenderClient(cc)
}

func (c *MessageSenderClientImpl2) XXX_InterfaceName() string {
	return "MessageSender"
}

type MessageSenderClientImpl3 struct {
	Send func(ctx context.Context, in *MessageRequest) (*MessageResponse, error)
}

func (c *MessageSenderClientImpl3) GetDubboStub(cc *triple.TripleConn) MessageSenderClient {
	return NewMessageSenderClient(cc)
}

func (c *MessageSenderClientImpl3) XXX_InterfaceName() string {
	return "MessageSender"
}

type MessageSenderClientImpl4 struct {
	Send func(ctx context.Context, in *MessageRequest) (*MessageResponse, error)
}

func (c *MessageSenderClientImpl4) GetDubboStub(cc *triple.TripleConn) MessageSenderClient {
	return NewMessageSenderClient(cc)
}

func (c *MessageSenderClientImpl4) XXX_InterfaceName() string {
	return "MessageSender"
}

type MessageSenderClientImpl5 struct {
	Send func(ctx context.Context, in *MessageRequest) (*MessageResponse, error)
}

func (c *MessageSenderClientImpl5) GetDubboStub(cc *triple.TripleConn) MessageSenderClient {
	return NewMessageSenderClient(cc)
}

func (c *MessageSenderClientImpl5) XXX_InterfaceName() string {
	return "MessageSender"
}

func NewMessageSenderClient(cc *triple.TripleConn) MessageSenderClient {
	return &messageSenderClient{cc}
}

func (c *messageSenderClient) Send(ctx context.Context, in *MessageRequest, opts ...grpc_go.CallOption) (*MessageResponse, common.ErrorWithAttachment) {
	out := new(MessageResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Send", in, out)
}

// MessageSenderServer is the server API for MessageSender service.
// All implementations must embed UnimplementedMessageSenderServer
// for forward compatibility
type MessageSenderServer interface {
	Send(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedMessageSenderServer()
}

// UnimplementedMessageSenderServer must be embedded to have forward compatible implementations.
type UnimplementedMessageSenderServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMessageSenderServer) Send(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (s *UnimplementedMessageSenderServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMessageSenderServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMessageSenderServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MessageSender_ServiceDesc
}
func (s *UnimplementedMessageSenderServer) XXX_InterfaceName() string {
	return "MessageSender"
}

func (UnimplementedMessageSenderServer) mustEmbedUnimplementedMessageSenderServer() {}

// UnsafeMessageSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageSenderServer will
// result in compilation errors.
type UnsafeMessageSenderServer interface {
	mustEmbedUnimplementedMessageSenderServer()
}

func RegisterMessageSenderServer(s grpc_go.ServiceRegistrar, srv MessageSenderServer) {
	s.RegisterService(&MessageSender_ServiceDesc, srv)
}

func _MessageSender_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Send", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MessageSender_ServiceDesc is the grpc_go.ServiceDesc for MessageSender service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageSender_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "MessageSender",
	HandlerType: (*MessageSenderServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MessageSender_Send_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "samples_api.proto",
}
