// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GprcMessageSenderClient is the client API for MessageSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GprcMessageSenderClient interface {
	Send(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	Close()
}

type grpcMessageSenderClient struct {
	cc *grpc.ClientConn
}

func NewGRpcMessageSenderClient(cc *grpc.ClientConn) GprcMessageSenderClient {
	return &grpcMessageSenderClient{cc}
}

func (c *grpcMessageSenderClient) Send(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/MessageSender/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcMessageSenderClient) Close() {
	c.cc.Close()
}

// GrpcMessageSenderServer is the server API for MessageSender service.
// All implementations must embed UnimplementedGprcMessageSenderServer
// for forward compatibility
type GrpcMessageSenderServer interface {
	Send(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedMessageSenderServer()
}

// UnimplementedGprcMessageSenderServer must be embedded to have forward compatible implementations.
type UnimplementedGprcMessageSenderServer struct {
}

func (UnimplementedGprcMessageSenderServer) Send(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGprcMessageSenderServer) mustEmbedUnimplementedMessageSenderServer() {}

// GprcUnsafeMessageSenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcMessageSenderServer will
// result in compilation errors.
type GprcUnsafeMessageSenderServer interface {
	mustEmbedUnimplementedMessageSenderServer()
}

func RegisterGprcMessageSenderServer(s grpc.ServiceRegistrar, srv GrpcMessageSenderServer) {
	s.RegisterService(&Grpc_MessageSender_ServiceDesc, srv)
}

func _Grpc_MessageSender_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcMessageSenderServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageSender/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcMessageSenderServer).Send(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Grpc_MessageSender_ServiceDesc is the grpc.ServiceDesc for MessageSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grpc_MessageSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageSender",
	HandlerType: (*GrpcMessageSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Grpc_MessageSender_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
